# Generated by Django 5.0.4 on 2024-05-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kimchi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="image",
            field=models.CharField(default="http", max_length=300),
        ),
    ]
