# Generated by Django 5.0.4 on 2024-05-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kimchi", "0002_menu_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="availability",
            field=models.BooleanField(default=False),
        ),
    ]
