# Generated by Django 5.0.4 on 2024-05-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kimchi", "0003_menu_availability"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("food", models.CharField(max_length=100)),
                ("quantity", models.CharField(max_length=100)),
            ],
        ),
    ]
