# Generated by Django 5.0.6 on 2024-05-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=100)),
                ('image', models.CharField(default='http', max_length=300)),
                ('ingredients', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=60)),
                ('availability', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('food', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('delivery_status', models.BooleanField(default=False)),
            ],
        ),
    ]
