# Generated by Django 5.0.6 on 2024-06-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='from_user',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='to_user',
            field=models.CharField(max_length=150),
        ),
    ]
